### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by danielsdesk** [Trudko/package-list-downloader#4]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
PackageListView.showPackageList (/Users/dhenning/.atom/packages/package-list-downloader/lib/package-list-downloader-view.js:34:7)
```

**Comment by Trudko** [comment]
Thanks! :) Didn't look at this package for quite some time. Out of curious how do you use it?
